USE [master]
GO

/****** Object:  Database [NSAppMonDB]    Script Date: 15.06.2020 08:55:09 ******/
CREATE DATABASE [NSAppMonDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NSAppMonDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\NSAppMonDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NSAppMonDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\NSAppMonDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NSAppMonDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NSAppMonDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NSAppMonDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NSAppMonDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NSAppMonDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NSAppMonDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [NSAppMonDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NSAppMonDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NSAppMonDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NSAppMonDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NSAppMonDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NSAppMonDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NSAppMonDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NSAppMonDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NSAppMonDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NSAppMonDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NSAppMonDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NSAppMonDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NSAppMonDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NSAppMonDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NSAppMonDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NSAppMonDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NSAppMonDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NSAppMonDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [NSAppMonDB] SET  MULTI_USER 
GO

ALTER DATABASE [NSAppMonDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NSAppMonDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NSAppMonDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NSAppMonDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [NSAppMonDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NSAppMonDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [NSAppMonDB] SET  READ_WRITE 
GO


USE [NSAppMonDB]
GO

/****** Object:  Table [dbo].[NSApplicationsT]    Script Date: 15.06.2020 08:56:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[NSApplicationsT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[UserID] [int] NOT NULL,
	[Interval] [int] NOT NULL,
	[URL] [nvarchar](max) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[UpdatedDate] [datetime] NULL,
 CONSTRAINT [PK_NSApplicationsT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[NSApplicationsT]  WITH CHECK ADD  CONSTRAINT [FK_NSApplicationsT_NSUsersT] FOREIGN KEY([UserID])
REFERENCES [dbo].[NSUsersT] ([ID])
GO

ALTER TABLE [dbo].[NSApplicationsT] CHECK CONSTRAINT [FK_NSApplicationsT_NSUsersT]
GO


USE [NSAppMonDB]
GO

/****** Object:  Table [dbo].[NSResourcesT]    Script Date: 15.06.2020 08:56:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[NSResourcesT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Language] [nvarchar](50) NOT NULL,
	[ResourceKey] [nvarchar](50) NOT NULL,
	[ResourceText] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_NSResourcesT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


USE [NSAppMonDB]
GO

/****** Object:  Table [dbo].[NSUsersT]    Script Date: 15.06.2020 08:56:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[NSUsersT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NOT NULL,
	[Mail] [nvarchar](50) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[UpdatedDate] [datetime] NULL,
 CONSTRAINT [PK_NSUsersT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


